### ISSUE TITLE
RingCentral recipes should be renamed "RingCentral Classic"

### ISSUE THREAD

**Issue by wegotoeleven** [autopkg/psaintemarie-recipes#2]
As per #1 - As the title suggests, this is to better differentiate the packages in AutoPkg.

**Comment by wegotoeleven** [comment]
Bump!

**Comment by wegotoeleven** [comment]
Bump again!

**Comment by wegotoeleven** [comment]
Bump a third time! ❤️

**Comment by psaintemarie** [comment]
Thanks for the PR and sorry for the lag :D
